#Change checkpoint and sense_map path
checkpoint_dir: /share/gpu0/jjwhit/mass_map/mm_models/
data_path: /share/gpu0/jjwhit/kappa_cosmos_simulations/cropped_dataset/
cosmo_dir_path: /home/jjwhit/rcGAN/mass_map_utils/cosmos/

# Define the experience
experience: mass_mapping
kappa_mean: 0.00015744006243248638 # Value calculated during preprocessing
kappa_std: 0.02968584954283938 # Value calculated during preprocessing

# Number of code vectors for each phase
num_z_test: 32
num_z_valid: 8
num_z_train: 2

# Data
in_chans: 4  # Real+Imag parts from observation + Kaiser squires map #TODO: If this works, add this to normal config
out_chans: 2
im_size: 300 # Pixel width/height (square iamges)

# Optimizer:
lr: 0.001
beta_1: 0
beta_2: 0.99

# Loss weights
gp_weight: 10
adv_weight: 1e-5

# Training
batch_size: 9
#Remember to increase this for full training
num_epochs: 10
psnr_gain_tol: 0.25

num_workers: 1